version: "3.2"
services:
  grpc:
    container_name: "bl-grpc"
    build:
      dockerfile: .dev/grpc.Dockerfile
      context: .
      args:
        CMD_SERVICE: grpc
    ports:
      - 50051:50051
  http-rest:
    container_name: "bl-rest"
    build:
      dockerfile: .dev/rest.Dockerfile
      context: .
      args:
        CMD_SERVICE: rest
    ports:
      - 50051:50051